#!/bin/bash

if [ $# -eq 4 ]; then

  instance="${1}"
  virtualhost="${2}"
  url="${3}"

  #
  # Handle alias open locations

  # find /etc/device/services/www/open/alias/ -mindepth 1 -maxdepth 1 -type l
  while read line; do

    if test ! -f "$line/virtualhost.d/listen.d/instance.d/name.txt" -o "${instance}" != "$(head -n 1 $line/virtualhost.d/listen.d/instance.d/name.txt)"; then
      continue;
    fi
    if test ! -f "$line/virtualhost.d/name.txt" -o "${virtualhost}" != "$(head -n 1 $line/virtualhost.d/name.txt)"; then
      continue;
    fi
    if test ! -f "$line/name.txt"; then
      continue;
    fi
    if test ! -L "$line/directory"; then
      continue;
    fi
    location="$(head -n 1 ${line}/name.txt)"
    directory="$(readlink -m ${line}/directory)"

    # read server-name if present
    if test -f "$line/virtualhost.d/server-name.txt"; then
      servername="$(head -n 1 $line/virtualhost.d/server-name.txt)"
    else
      servername="$(hostname -f)"
    fi

    # read in the path if present
    path=""
    if test -f "${line}/path.txt"; then
      path="$(head -n 1 ${line}/path.txt)"
    fi
    # empty path becomes a /
    if test -z "${path}";then
      path="/"
    fi

    # read auth if present
    # Note: "open" MAY be open, MAY be locked, and MAY be misconfigured
    authname=""
    if test -f "$line/auth.d/name.txt"; then
      authname="$(head -n 1 $line/auth.d/name.txt)"
    fi

    echo
    echo "    Open alias + ${location}:"
    echo "      url: ${url}${path}"
    echo "      directory: ${directory}"

    if test -n "${authname}"; then
      echo "      auth: ${authname}"
    else
      echo "      no-auth: open"
    fi

  done < <(find /etc/device/services/www/open/alias/ -mindepth 1 -maxdepth 1 -type l)

fi


