#!/bin/bash

if [ $# -eq 3 ]; then

  instance="${1}"
  virtualhost="${2}"

  #
  # Handle dav locations
  
  # find /etc/device/services/www/dav/ -mindepth 1 -maxdepth 1 -type l
  while read line; do

    if test ! -f "$line/virtualhost.d/listen.d/instance.d/name.txt" -o "${instance}" != "$(head -n 1 $line/virtualhost.d/listen.d/instance.d/name.txt)"; then
      continue;
    fi
    if test ! -f "$line/virtualhost.d/name.txt" -o "${virtualhost}" != "$(head -n 1 $line/virtualhost.d/name.txt)"; then
      continue;
    fi
    if test ! -f "$line/name.txt"; then
      continue;
    fi
    if test ! -L "$line/directory"; then
      continue;
    fi
    location="$(head ${line}/name.txt)"
    directory="$(readlink -f ${line}/directory)"

    # read in the path if present
    path=""
    if test -f "${line}/path.txt"; then
      path="$(head ${line}/path.txt)"
    fi
    # empty path becomes a /
    if test -z "${path}";then
      path="/"
    fi

    cat >> "device-${instance}-${virtualhost}-${location}.conf" <<- EOF
<IfModule !alias_module>
  LoadModule alias_module modules/mod_alias.so
</IfModule>
<IfModule !authz_user_module>
  LoadModule authz_user_module modules/mod_authz_user.so
</IfModule>
<IfModule !autoindex_module>
  LoadModule autoindex_module modules/mod_autoindex.so
</IfModule>
<IfModule !dav_module>
  LoadModule dav_module modules/mod_dav.so
</IfModule>
<IfModule !dav_fs_module>
  LoadModule dav_fs_module modules/mod_dav_fs.so
</IfModule>

# DAV configured from ${line}/path.txt
  <Location ${path}>
    Alias ${directory}
    DirectoryIndex disabled
  </Location>

  <Directory ${directory}>
    Dav on
    Options +Indexes

    IndexOptions FancyIndexing HTMLTable VersionSort XHTML

#    HeaderName /storage-assets/HEADER.html
#    ReadmeName /storage-assets/FOOTER.html

    AuthzSendForbiddenOnFailure on

    SSLUserName SSL_CLIENT_CERT_RFC4523_CEA

    <Limit GET POST PUT DELETE PROPFIND PROPPATCH MKCOL COPY DUPLICATE MOVE LOCK UNLOCK OPTIONS HEAD>
      require valid-user
    </Limit>

EOF

    cat >> "device-${instance}-${virtualhost}-${location}.conf" <<- EOF
  </Directory>
EOF

    install "device-${instance}-${virtualhost}-${location}.conf" "/etc/httpd/conf.device.d/instance/${instance}/secure-${virtualhost}.d/location-$(echo ${path} | tr [:cntrl:][:punct:] _).conf"

  done < <(find /etc/device/services/www/dav/ -mindepth 1 -maxdepth 1 -type l)

fi


