#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --hostname name \
	 --show-flags disabled --show-table name,virtualhost,path,redirect --flag X \
         --polar disabled \
         --required \
         --url-path-absolute path \
         --relation-base /etc/device/services/www/virtualhost --relation-name name --relation-suffix .txt --relation virtualhost \
         --uri redirect"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

