#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --required --uri-schemes https --uri-absolute url --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink tls-ca-certs"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

