#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --hostname name --show-table name,https,url,tls-ca-certs --required --uri-schemes https --uri-absolute url --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink tls-ca-certs"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

