#!/bin/sh

set -e
umask 0002

OPTIONS="--show name \
	 --hostname name \
	 --show-flags disabled \
	 --show-table name,virtualhost,path,directory,auth \
	 --flag X --polar disabled \
	 --uri access-url \
	 --required \
	 --url-path-absolute path \
	 --relation-base /etc/device/services/www/virtualhost --relation-name name --relation-suffix .txt --relation virtualhost \
	 --symlink-base /var/www/safe/home/ --symlink directory \
	 --relation-base /etc/device/services/www/auth --relation-name name --relation-suffix .txt --relation auth "

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

