#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

OPTIONS="--add name --hostname name --polar disabled --relation-base /etc/device/services/ldap/suffix --relation-name name --relation-suffix .txt --relation ldap-suffix --distinguished-name ldap-group --required"

# --symlink-context-type httpd_sys_rw_content_t 

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

