#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --required --fqdn server-name --relation-base /etc/device/services/www/listen --relation-name name --relation-suffix .txt --relation listen"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@" | cat

fi

