#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --select-base /usr/libexec/device/services/www/virtualhost/tls-verify.txt --select tls-verify --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink tls-ca-certs --required --fqdn server-name --relation-base /etc/device/services/www/listen --relation-name name --relation-suffix .txt --relation listen"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@" | cat

fi

