#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

OPTIONS="--add name --hostname name --polar disabled --text access-url --required --relation-base /etc/device/services/www/auth --relation-name name --relation-suffix .txt --relation auth --url-path-absolute path --relation-base /etc/device/services/www/virtualhost --relation-name name --relation-suffix .txt --relation virtualhost --symlink-base /var/www/safe/alias --symlink directory"

# --symlink-context-type httpd_sys_rw_content_t 

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

