#!/bin/bash
  
#
# Apache httpd Server Postdiscovery
# =================================
#
# This script autogenerates any required httpd configuration after startup.

set -e


#
# Handle the cleanup
# ------------------
cleanup_before_exit () {
  if [ -d "${tmpdir}" ]; then
    rm -rf "${tmpdir}"
  fi
}
# be in a temporary workspace (this works on linux and macosx)
tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
# trap catches the exit signal and runs the specified function
trap cleanup_before_exit EXIT
# be in our directory
cd "${tmpdir}"



#
# Per instance? Run all scripts

logger -t "httpd-postdiscovery" "running postdiscovery for httpd servers..."

find "$0.d" -type f -executable | sort | \
while read x; do
  "$x" < /dev/null || touch error;
done

if test ! -f "error"; then
  logger -t "httpd-postdiscovery" "completed postdiscovery for httpd servers."
  exit 0
else
  logger -t "httpd-postdiscovery" "failed postdiscovery for httpd servers."
  exit 1
fi

