#!/bin/sh

#
# Apache httpd Server Status
# ==========================
#
# This script generates a dynamic status of the configuration.

set -e


echo
echo "Webserver:"

# find /etc/device/services/www/instance/ -mindepth 1 -maxdepth 1 -type l
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head $line/name.txt)"

  if test -f "$line/disabled.bin"; then
    echo "- httpd@device-${instance}: disabled"
  elif systemctl is-failed --quiet httpd-autodiscovery.service; then
    echo "- httpd@device-${instance}: autodiscovery-failed"
  elif systemctl is-active --quiet httpd-autodiscovery.service; then
    echo -n "- httpd@device-${instance}: "
    SYSTEMD_COLORS=1 systemctl is-active "httpd@device-${instance}" || true
    if test -r "/etc/httpd/conf/device-${instance}.conf"; then
      echo -n "  configtest: "
      /usr/sbin/httpd -t -f /etc/httpd/conf/device-${instance}.conf || true
    fi
  elif systemctl is-enabled --quiet httpd-autodiscovery.service; then
    echo "- httpd@device-${instance}: scheduled-for-startup"
  else
    echo "- httpd@device-${instance}: autodiscovery-disabled"
  fi

  found="found"

  /usr/bin/sequence "/usr/libexec/device-status/httpd.d" "${instance}" "${line}"

done < <(find /etc/device/services/www/instance/ -mindepth 1 -maxdepth 1 -type l)

if test -z "found"; then
  echo "- Status: no webserver instances exist"
fi

