#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --relation-base /etc/device/services/www/mpm --relation-name name --relation-suffix .txt --relation mpm --required"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

