#!/bin/sh
  
set -e
umask 0002

OPTIONS="--show name --hostname name --polar disabled --relation-base /etc/device/services/www/mpm --relation-name name --relation-suffix .txt --relation mpm --required"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi


