#!/bin/sh

set -e
umask 0002

OPTIONS="--set name --hostname name --polar disabled --integer-minimum 1 --integer max --integer-minimum 0 --integer acquire --uri access-url --relation-base /etc/device/services/www/auth --relation-name name --relation-suffix .txt --relation auth --required --url-path-absolute path --relation-base /etc/device/services/www/virtualhost --relation-name name --relation-suffix .txt --relation virtualhost --relation-base /etc/device/services/www/remote --relation-name name --relation-suffix .txt --relation remote"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart httpd-autodiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

